data:
  batch_size: 16
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224  
  image_folder: cifar-10.batches-py  
  num_workers: 10
  pin_mem: true
  root_path: data/cifar-10-batches-py
  use_horizontal_flip: true
  use_color_distortion: true
  use_gaussian_blur: false
logging:
  folder: logs
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 16
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_small
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: False
optimization:
  ema:
  - 0.996
  - 1.0
  epochs:  600 #1000000/50000 * num_epochs = 20 * 600 or 300
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001
  start_lr: 0.0002
  warmup: 40
  weight_decay: 0.04
